### ISSUE TITLE
Add contract test coverage for the RemoteSettings provider

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#143]
The automated system tests for Merino currently only exercise the `WikiFruit` provider.

From `config/ci.yaml`:

```yaml
# The suggestion providers to enable
suggestion_providers:
  test:
    type: "wiki_fruit"
```

This ticket is for developing at least one additional system test that verifies Merino returns matching suggestions from Remote Settings for HTTP requests to the `/api/v1/suggest` API endpoint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1287)
┆Epic: merino-milestone-1
